window.addEventListener('load',function(){
    document.getElementById('subject').addEventListener('mouseover',function(){
        document.getElementById('subject').classList.add('font-color-yellow');
        document.getElementById('contain').classList.add('add_box_shadow');
    })
    document.getElementById('subject').addEventListener('mouseout',function(){
        document.getElementById('subject').classList.remove('font-color-yellow');
        document.getElementById('contain').classList.remove('add_box_shadow');
    })
})